import express from "express";
import { chromium } from "playwright";
const app=express(); app.use(express.json({limit:"1mb"})); const PORT=process.env.PORT||10000;
const personal=/cpf|whatsapp|telefone|celular|e-mail|email|senha|login|documento|nascimento/i;
const commitment=/contrat|assinar|fidelidade|pagamento|cart[aã]o|cancelar|finalizar|confirmar pedido/i;
const support=/chat|assistente virtual|fale conosco|falar com|suporte|ajuda|negoci|renegoci|atendimento/i;
const wrongChannel=/fornecedor|carreira|trabalhe conosco|empresarial|empresa|corporativo|imprensa|ouvidoria/i;
app.get("/health",(_,res)=>res.json({ok:true,service:"resolva-executor",engine:"playwright"}));
async function allText(page){let out="";for(const f of page.frames()){out+="\n"+await f.locator("body").innerText().catch(()=>"");}return out.slice(-30000);}
async function clickLeadster(page){const sels=['[class*="leadster"]','[id*="leadster"]','iframe[src*="leadster"]','button[aria-label*="chat" i]','button[title*="chat" i]'];for(const sel of sels){const el=page.locator(sel).first();if(await el.count().catch(()=>0)){if(sel.startsWith("iframe")){const box=await el.boundingBox().catch(()=>null);if(box){await page.mouse.click(box.x+box.width-28,box.y+box.height-28).catch(()=>{});await page.waitForTimeout(1800);return true;}}else if(await el.isVisible().catch(()=>false)){await el.click({force:true,timeout:2500}).catch(()=>{});await page.waitForTimeout(1800);return true;}}}const html=(await page.content().catch(()=>"")).toLowerCase();if(html.includes("leadster")){const vp=page.viewportSize()||{width:1280,height:720};await page.mouse.click(vp.width-45,vp.height-45).catch(()=>{});await page.waitForTimeout(1800);return true;}return false;}
async function openSupport(page){if(await clickLeadster(page))return true;for(const f of page.frames()){const els=f.locator('button,a,[role="button"]');const n=Math.min(await els.count().catch(()=>0),120);for(let i=0;i<n;i++){const e=els.nth(i);if(!await e.isVisible().catch(()=>false))continue;const t=((await e.innerText().catch(()=>""))+" "+(await e.getAttribute("aria-label").catch(()=>""))+" "+(await e.getAttribute("title").catch(()=>""))).trim();if(support.test(t)&&!commitment.test(t)&&!wrongChannel.test(t)){await e.click({timeout:2500}).catch(()=>{});await page.waitForTimeout(1800);return true;}}}return false;}
async function advanceChat(page){for(let round=0;round<4;round++){let moved=false;for(const f of page.frames()){const buttons=f.locator('button,[role="button"],a');const n=Math.min(await buttons.count().catch(()=>0),80);for(let i=0;i<n;i++){const b=buttons.nth(i);if(!await b.isVisible().catch(()=>false))continue;const t=((await b.innerText().catch(()=>""))+" "+(await b.getAttribute("aria-label").catch(()=>""))).trim();if(!t||personal.test(t)||commitment.test(t)||wrongChannel.test(t))continue;if(/continuar|começar|iniciar|vamos lá|quero atendimento|falar com atendente|sou cliente|cliente|residencial/i.test(t)){await b.click({timeout:2000}).catch(()=>{});await page.waitForTimeout(1400);moved=true;break;}}if(moved)break;}if(!moved)break;}return true;}
async function sendMessage(page,message){for(const f of page.frames()){const inputs=f.locator('textarea,input[type="text"],[contenteditable="true"]');const n=Math.min(await inputs.count().catch(()=>0),30);for(let i=0;i<n;i++){const input=inputs.nth(i);if(!await input.isVisible().catch(()=>false))continue;const meta=((await input.getAttribute("placeholder").catch(()=>""))+" "+(await input.getAttribute("aria-label").catch(()=>""))).trim();if(personal.test(meta)||commitment.test(meta))continue;await input.fill(message).catch(()=>{});const filled=(await input.inputValue().catch(()=>""))||(await input.textContent().catch(()=>""));if(!filled)continue;const buttons=f.locator('button,[role="button"]');const m=Math.min(await buttons.count().catch(()=>0),50);for(let j=0;j<m;j++){const b=buttons.nth(j);if(!await b.isVisible().catch(()=>false))continue;const bt=((await b.innerText().catch(()=>""))+" "+(await b.getAttribute("aria-label").catch(()=>""))+" "+(await b.getAttribute("title").catch(()=>""))).trim();if(/enviar|send|continuar|avançar|prosseguir/i.test(bt)&&!commitment.test(bt)){await b.click({timeout:2500}).catch(()=>{});await page.waitForTimeout(2200);return true;}}return false;}}return false;}
app.post("/execute",async(req,res)=>{const {targetUrl,message}=req.body||{};if(!targetUrl||!/^https:\/\//i.test(targetUrl)||!message)return res.status(400).json({error:"targetUrl e message obrigatorios"});let browser;try{browser=await chromium.launch({headless:true,args:["--no-sandbox","--disable-dev-shm-usage"]});const ctx=await browser.newContext({locale:"pt-BR"});const page=await ctx.newPage();await page.goto(targetUrl,{waitUntil:"domcontentloaded",timeout:45000});await page.waitForTimeout(7000);const title=await page.title();const opened=await openSupport(page);await page.waitForTimeout(1500);let text=await allText(page);await advanceChat(page);const sent=await sendMessage(page,message);if(!sent)return res.json({status:"APPROVAL_REQUIRED",engine:"SELF_HOSTED",externalCost:false,summary:opened?"Abri o atendimento real, mas não encontrei um envio seguro para a mensagem.":"Abri o site, mas não consegui identificar o chat de atendimento com segurança.",title,url:page.url(),blocker:opened?"NO_SAFE_SUBMIT":"CHAT_NOT_FOUND",chatOpened:opened});text=await allText(page);const blocked=personal.test(text.slice(-7000))||commitment.test(text.slice(-7000));return res.json({status:blocked?"APPROVAL_REQUIRED":"COMPLETED",engine:"SELF_HOSTED",externalCost:false,summary:blocked?"Enviei a solicitação inicial. O próximo passo pede dado pessoal, autenticação ou compromisso; parei aqui.":"Solicitação inicial enviada ao atendimento real.",title,url:page.url(),blocker:blocked?"PERSONAL_DATA_OR_COMMITMENT":null,chatOpened:true,messageSent:true,responseExcerpt:text.slice(-1200)});}catch(e){return res.status(500).json({status:"FAILED",engine:"SELF_HOSTED",externalCost:false,error:String(e?.message||e)});}finally{if(browser)await browser.close().catch(()=>{});}});
app.listen(PORT,"0.0.0.0",()=>console.log("resolva-executor listening",PORT));
